module:
  admin_toolbar: 0
  admin_toolbar_tools: 0
  block: 0
  breakpoint: 0
  ckeditor: 0
  codetag: 0
  dblog: 0
  dynamic_page_cache: 0
  editor: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  highlightphp: 0
  image: 0
  metatag: 0
  metatag_open_graph: 0
  metatag_twitter_cards: 0
  mortenson_components: 0
  node: 0
  page_cache: 0
  path: 0
  path_alias: 0
  responsive_image: 0
  serialization: 0
  sfc: 0
  sfc_dev: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  tome: 0
  tome_base: 0
  tome_static: 0
  tome_sync: 0
  toolbar: 0
  twig_tweak: 0
  update: 0
  user: 0
  minimal: 1000
theme:
  stable: 0
  classy: 0
  claro: 0
  mortenson: 0
profile: minimal
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
